DROP TABLE Users;

DROP TABLE Users IF EXISTS;

INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 10 INCREMENT BY 10),


CREATE TABLE Users
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY 
            (START WITH 1, INCREMENT BY 1),
username VARCHAR(255),
highscore VARCHAR(255),
PRIMARY KEY(ID)
);



INSERT INTO Users(username, highscore)
       VALUES
        ('Benutzer1', '120'),
       ('Benutzer2', '130');


INSERT INTO Users 
VALUES (1, 'Benutzer1', '120');
;

Delete FROM Users where ID=3;
DELETE FROM Users;

UPDATE Users  SET username='Michel', highscore='120' WHERE ID = 1;


Select * from Users;

DELETE FROM Users;